WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015A416529D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/23cc806f8d6336922c6013de8cff765d
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015A42D89890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/23cc806f8d6336922c6013de8cff765d
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015A42D88610>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/23cc806f8d6336922c6013de8cff765d
